//! v1.7 PR-A1 — `dialect_signals` cross-consistency CI guard.
//!
//! The v1.6 architecture audit (Important #3) flagged a drift hazard:
//! three separate sources of truth for "what is a pandas-side
//! method" (`PANDAS_DISCRIMINATORS` in `alias_adjudicate.rs`,
//! `SPARK_DISCRIMINATORS` in the same file, and inline `matches!`
//! arms guarded by `receiver_is_pandas_inherited` in
//! `operations/expr.rs`). Adding a new pandas-dispatched arm in
//! `expr.rs` did not force the discriminator lists to update, and
//! vice versa. PR-A1 collected the lists into the shared
//! `dialect_signals` module; this test enforces that every method
//! named in an `expr.rs` pandas-dispatched arm lives in EITHER
//! [`PANDAS_ONLY_SIGNALS`] OR [`PANDAS_INHERITED_ARMS`] — never
//! neither.
//!
//! **v1.8 PR-A1 update**: the inventory is now generated by
//! `crates/pykrete/build.rs` from `operations/expr.rs` at compile time
//! and exposed as [`PANDAS_INHERITED_ARM_METHODS_GENERATED`]. The
//! hand-maintained const below is kept as a tripwire — a contributor
//! who edits `expr.rs` without updating the hand list trips
//! `v18_pr_a1_hand_inventory_matches_generated`. Closes v1.7 retro
//! rule 4 (within-cycle inventory drift).

use pykrete::{PANDAS_INHERITED_ARM_METHODS_GENERATED, PANDAS_INHERITED_ARMS, PANDAS_ONLY_SIGNALS};

/// Every method name appearing in an `expr.rs` arm gated by
/// `receiver_is_pandas_inherited`. The live inventory is generated by
/// `crates/pykrete/build.rs::extract_methods` by scanning
/// `operations/expr.rs` for `receiver_is_pandas_inherited && ...`
/// patterns; line numbers shift across cycles, so the doc-comment
/// references the generator (the source of truth) rather than pinning
/// line offsets that go stale. Hand list kept as a redundant tripwire
/// vs the build-script-generated const; if they disagree,
/// `v18_pr_a1_hand_inventory_matches_generated` fails.
/// v1.9 PR-A1 (arch-N1): dropped stale line numbers.
const PANDAS_INHERITED_ARM_METHODS: &[&str] = &[
    "head",
    "tail",
    "first",
    "take",
    "rename",
    "assign",
    "drop",
    "pivot_table",
    "melt",
];

/// Every method in the `expr.rs` pandas-arm inventory above must
/// appear in either [`PANDAS_ONLY_SIGNALS`] or [`PANDAS_INHERITED_ARMS`].
/// The failure mode this catches: a contributor adds a new
/// `receiver_is_pandas_inherited && method == "M"` arm to `expr.rs`,
/// updates this inventory, but forgets to add `M` to either list.
#[test]
fn v17_pr_a1_every_arm_method_is_listed() {
    for method in PANDAS_INHERITED_ARM_METHODS_GENERATED {
        let in_only = PANDAS_ONLY_SIGNALS.contains(method);
        let in_inherited = PANDAS_INHERITED_ARMS.contains(method);
        assert!(
            in_only || in_inherited,
            "expr.rs uses method '{method}' in a pandas-dispatched arm, but \
             '{method}' is in neither PANDAS_ONLY_SIGNALS nor \
             PANDAS_INHERITED_ARMS. Add it to one (or the test inventory \
             above is stale and should be updated to match expr.rs)."
        );
    }
}

/// Disjointness — a method either tags the binding (pandas-only name)
/// or shares the dispatch surface (inherited from Spark). It can't do
/// both; that's the semantic split documented in
/// `crates/pykrete/src/dialect_signals.rs`. If `head` ever leaks into
/// `PANDAS_ONLY_SIGNALS`, every Spark codebase calling `df.head()`
/// suddenly classifies as Pandas (false-positive D0090 adjudication);
/// if `assign` ever leaks into `PANDAS_INHERITED_ARMS`, the meaning of
/// the list — "shared-with-Spark" — is corrupted.
#[test]
fn v17_pr_a1_only_signals_and_inherited_arms_are_disjoint() {
    for method in PANDAS_ONLY_SIGNALS {
        assert!(
            !PANDAS_INHERITED_ARMS.contains(method),
            "'{method}' appears in both PANDAS_ONLY_SIGNALS and \
             PANDAS_INHERITED_ARMS. The two lists must be disjoint per \
             the dialect_signals module doc — pandas-only names tag \
             bindings; shared-with-Spark names route dispatch arms."
        );
    }
}

/// Sanity pin: the generated inventory length is what the v1.8 PR-A1
/// CI-guard considers "complete". A contributor adding a new arm in
/// `expr.rs` causes the build-script extraction to grow; the pin
/// surfaces the change in code review and forces an explicit count
/// update here.
#[test]
fn v18_pr_a1_inventory_has_nine_methods() {
    assert_eq!(
        PANDAS_INHERITED_ARM_METHODS_GENERATED.len(),
        9,
        "expr.rs pandas-arm inventory pinned at 9 methods as of v1.8 \
         PR-A1; if you're seeing this fail you've added/removed an arm \
         in operations/expr.rs and the build-script regenerated the \
         inventory. Update this pin to match and verify any associated \
         discriminator-list updates landed too."
    );
}

/// v1.8 PR-A1 tripwire — the hand-maintained inventory above MUST
/// equal the build-script-generated inventory (as sorted sets). Closes
/// v1.7 retro rule 4: within-cycle drift between the hand list and the
/// live `expr.rs` arms. A contributor who adds an arm to `expr.rs`
/// without updating the hand list trips this; equally, a contributor
/// who edits the hand list without an `expr.rs` change is told to
/// undo it.
#[test]
fn v18_pr_a1_hand_inventory_matches_generated() {
    let mut hand: Vec<&str> = PANDAS_INHERITED_ARM_METHODS.to_vec();
    let mut generated: Vec<&str> = PANDAS_INHERITED_ARM_METHODS_GENERATED.to_vec();
    hand.sort();
    hand.dedup();
    generated.sort();
    generated.dedup();
    assert_eq!(
        hand, generated,
        "hand-maintained PANDAS_INHERITED_ARM_METHODS in tests/v17_pr_a1_dialect_signals_guard.rs \
         disagrees with build-script-generated PANDAS_INHERITED_ARM_METHODS_GENERATED. \
         The generated list is the source of truth (extracted from operations/expr.rs by \
         crates/pykrete/build.rs). Either (a) you added/removed an arm in expr.rs and forgot \
         to update the hand list, or (b) you edited the hand list without a corresponding \
         expr.rs change. Reconcile and re-run."
    );
}

/// Regression guard for the load-bearing case: `head` MUST live in
/// `PANDAS_INHERITED_ARMS` only. The v1.5 PR-A3 / v1.6 PR-A2 schema
/// preservation through `pdf.head().assign(...)` depends on the
/// `receiver_is_pandas_inherited && matches!(method, "head" | ...)`
/// arm in `expr.rs` firing — which references the list. If `head`
/// accidentally moves to `PANDAS_ONLY_SIGNALS` the dispatch classifies
/// Spark `df.head()` as Pandas and the schema mutates silently.
#[test]
fn v17_pr_a1_head_is_only_in_inherited_arms() {
    assert!(
        PANDAS_INHERITED_ARMS.contains(&"head"),
        "head must remain in PANDAS_INHERITED_ARMS — the expr.rs arm \
         depends on it for the schema pass-through.",
    );
    assert!(
        !PANDAS_ONLY_SIGNALS.contains(&"head"),
        "head must NOT be in PANDAS_ONLY_SIGNALS — Spark `df.head()` \
         exists too; classifying on `head` would false-positive D0090 \
         on every Spark codebase.",
    );
}

/// Regression guard for the other load-bearing case: `assign` MUST
/// live in `PANDAS_ONLY_SIGNALS` only. The adjudicator in
/// `alias_adjudicate.rs` walks downstream usage and tags a binding as
/// Pandas if it sees a pandas-only signal. `assign` is the canonical
/// example.
#[test]
fn v17_pr_a1_assign_is_only_in_pandas_only_signals() {
    assert!(
        PANDAS_ONLY_SIGNALS.contains(&"assign"),
        "assign must remain in PANDAS_ONLY_SIGNALS — the call-graph \
         adjudicator relies on it to classify pandas bindings.",
    );
    assert!(
        !PANDAS_INHERITED_ARMS.contains(&"assign"),
        "assign must NOT be in PANDAS_INHERITED_ARMS — it has no Spark \
         counterpart; the list is for shared-with-Spark names only.",
    );
}
