//! v1.8 PR-A1 — generate `PANDAS_INHERITED_ARM_METHODS_GENERATED` from
//! the live `operations/expr.rs` source.
//!
//! v1.7 retro rule 4: the hand-maintained inventory in
//! `tests/v17_pr_a1_dialect_signals_guard.rs` drifted within a single
//! cycle (PR-D1 added a `melt` arm; the hand-list missed it; PR-G
//! patched). The fix is to make the inventory a build-time extraction
//! from the source-of-truth `expr.rs`. A consumer-side equality test
//! (`v18_pr_a1_hand_inventory_matches_generated`) then keeps the
//! hand-list honest, OR makes deletion trivial.
//!
//! Patterns matched (both are gated by `receiver_is_pandas_inherited &&`):
//!
//!   • `receiver_is_pandas_inherited && matches!(method, "A" | "B" | ...)`
//!     — multi-line tolerant; extracts every string literal inside the
//!     `matches!` arm list.
//!   • `receiver_is_pandas_inherited && method == "X"`
//!     — multi-line tolerant; extracts the single string literal.
//!
//! If you change the syntax of either pattern in `expr.rs`, update
//! `extract_methods` below in lockstep. The tripwire comment near the
//! first `receiver_is_pandas_inherited` use in `expr.rs` names this
//! file.

use std::env;
use std::fs;
use std::path::PathBuf;

const EXPR_RS_RELATIVE: &str = "src/operations/expr.rs";
const GATE: &str = "receiver_is_pandas_inherited";

fn main() {
    println!("cargo:rerun-if-changed={EXPR_RS_RELATIVE}");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let expr_path = PathBuf::from(&manifest_dir).join(EXPR_RS_RELATIVE);
    let raw = fs::read_to_string(&expr_path)
        .unwrap_or_else(|e| panic!("read {}: {}", expr_path.display(), e));
    let source = strip_line_comments(&raw);

    let mut methods = extract_methods(&source);
    methods.sort();
    methods.dedup();

    let entries = methods
        .iter()
        .map(|m| format!("    {:?},", m))
        .collect::<Vec<_>>()
        .join("\n");
    let generated = format!(
        "// @generated by crates/pykrete/build.rs — do not edit by hand.\n\
         //\n\
         // Extracted from `src/operations/expr.rs` by scanning for the two\n\
         // `receiver_is_pandas_inherited &&` arm shapes. Re-run on every\n\
         // `cargo build` (cargo:rerun-if-changed). Consumed by\n\
         // `dialect_signals.rs` (re-export) and by\n\
         // `tests/v17_pr_a1_dialect_signals_guard.rs` (equality tripwire).\n\
         pub const PANDAS_INHERITED_ARM_METHODS_GENERATED: &[&str] = &[\n{entries}\n];\n"
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = PathBuf::from(&out_dir).join("pandas_inherited_arm_methods.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("write {}: {}", out_path.display(), e));
}

/// Replace every `// ...\n` line comment with spaces (preserving line
/// breaks so error byte offsets stay roughly meaningful). String
/// literals are honored — `"// not a comment"` stays intact. Block
/// comments `/* ... */` are NOT handled (Rust's `///` doc comments are
/// line comments, and `expr.rs` has no block comments). Without this,
/// the build.rs would extract method names quoted INSIDE doc comments
/// describing the arm shape — false positives.
fn strip_line_comments(src: &str) -> String {
    let bytes = src.as_bytes();
    let mut out = String::with_capacity(src.len());
    let mut i = 0;
    let mut in_str = false;
    let mut esc = false;
    while i < bytes.len() {
        let c = bytes[i];
        if in_str {
            out.push(c as char);
            if esc {
                esc = false;
            } else if c == b'\\' {
                esc = true;
            } else if c == b'"' {
                in_str = false;
            }
            i += 1;
            continue;
        }
        if c == b'"' {
            in_str = true;
            out.push('"');
            i += 1;
            continue;
        }
        if c == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/' {
            // Skip to end of line, replacing comment bytes with spaces
            // so byte offsets don't shift.
            while i < bytes.len() && bytes[i] != b'\n' {
                out.push(' ');
                i += 1;
            }
            continue;
        }
        out.push(c as char);
        i += 1;
    }
    out
}

/// Walk the source looking for `receiver_is_pandas_inherited` occurrences.
/// For each match, scan forward through the AND-conjoined predicate
/// (across newlines) and extract every quoted method-name from either a
/// `matches!(method, "X" | "Y" | ...)` arm or a `method == "X"` arm.
///
/// Hand-rolled rather than regex'd to avoid pulling `regex` into
/// pykrete's build closure. The patterns are simple enough — both
/// shapes are deliberately constrained in `expr.rs` per the tripwire
/// comment there.
fn extract_methods(source: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = source.as_bytes();
    let mut i = 0;
    while let Some(rel) = find_from(source, i, GATE) {
        let after = rel + GATE.len();
        // Walk forward through the conjoined predicate. Stop at `{` (start
        // of the arm body) or `;` (end of any expression statement). Skip
        // whitespace, newlines, and `&&` joiners between tokens.
        let mut j = after;
        let body_start = scan_to_body_or_semi(bytes, j);
        let region = &source[j..body_start];
        j = body_start;

        // Two extraction shapes inside `region`:
        //   • `matches!(method, "A" | "B" | ...)` — find the `matches!(`
        //     opener and grab every quoted literal until the matching `)`.
        //   • `method == "X"` — find `method` `==` `"…"` and grab the
        //     single literal.
        let mut found_any = false;

        if let Some(m_start) = region.find("matches!") {
            let after_macro = m_start + "matches!".len();
            if let Some(paren_open_rel) = region[after_macro..].find('(') {
                let paren_open_abs = after_macro + paren_open_rel + 1;
                if let Some(paren_close_abs) = find_matching_paren(region, paren_open_abs) {
                    let inner = &region[paren_open_abs..paren_close_abs];
                    for lit in extract_string_literals(inner) {
                        out.push(lit);
                        found_any = true;
                    }
                }
            }
        }

        // Independent scan for `method == "X"` arms; an arm could in
        // theory have both shapes but in practice `expr.rs` uses one
        // OR the other. Treat the two extractions as additive — if both
        // fire we collect both; the caller dedups.
        if let Some(eq_idx) = find_method_eq(region) {
            let rest = &region[eq_idx..];
            if let Some(lit) = extract_first_string_literal(rest) {
                out.push(lit);
                found_any = true;
            }
        }

        // Defensive: if we found NEITHER shape in the predicate region,
        // it likely means a new shape was introduced. Fail the build
        // loudly rather than silently dropping the arm. Skip the
        // `let receiver_is_pandas_inherited = ...` binding line.
        if !found_any && !region.contains('=') {
            panic!(
                "build.rs: found `{GATE}` at byte offset {rel} but neither \
                 `matches!(method, ...)` nor `method == \"...\"` followed. \
                 Update build.rs's extract_methods OR adjust the new arm \
                 shape in operations/expr.rs to match an existing pattern. \
                 Region: {:?}",
                region
            );
        }

        i = j.max(rel + 1);
    }
    out
}

fn find_from(haystack: &str, start: usize, needle: &str) -> Option<usize> {
    haystack[start..].find(needle).map(|r| start + r)
}

/// Advance from `i` to the byte index of the next `{` (arm body open) or
/// `;` (statement terminator) at the same brace-depth — whichever comes
/// first. Used to bound the predicate-region scan so we don't pull
/// literals out of the arm body itself.
fn scan_to_body_or_semi(bytes: &[u8], start: usize) -> usize {
    let mut depth_paren: i32 = 0;
    let mut depth_bracket: i32 = 0;
    let mut in_str = false;
    let mut esc = false;
    let mut i = start;
    while i < bytes.len() {
        let c = bytes[i];
        if in_str {
            if esc {
                esc = false;
            } else if c == b'\\' {
                esc = true;
            } else if c == b'"' {
                in_str = false;
            }
            i += 1;
            continue;
        }
        match c {
            b'"' => in_str = true,
            b'(' => depth_paren += 1,
            b')' => depth_paren -= 1,
            b'[' => depth_bracket += 1,
            b']' => depth_bracket -= 1,
            b'{' | b';' if depth_paren == 0 && depth_bracket == 0 => return i,
            _ => {}
        }
        i += 1;
    }
    bytes.len()
}

/// Find the index of the `)` that closes the `(` at `open` (which is the
/// position JUST AFTER the open paren — i.e. of the first byte inside).
/// Returns the position of the matching `)` (i.e. one past the inside).
fn find_matching_paren(s: &str, open_after: usize) -> Option<usize> {
    let bytes = s.as_bytes();
    let mut depth: i32 = 1;
    let mut in_str = false;
    let mut esc = false;
    let mut i = open_after;
    while i < bytes.len() {
        let c = bytes[i];
        if in_str {
            if esc {
                esc = false;
            } else if c == b'\\' {
                esc = true;
            } else if c == b'"' {
                in_str = false;
            }
        } else {
            match c {
                b'"' => in_str = true,
                b'(' => depth += 1,
                b')' => {
                    depth -= 1;
                    if depth == 0 {
                        return Some(i);
                    }
                }
                _ => {}
            }
        }
        i += 1;
    }
    None
}

/// Scan `s` and collect every double-quoted string literal inside it.
/// Used for the `matches!` arm list.
fn extract_string_literals(s: &str) -> Vec<String> {
    let mut out = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            let mut j = i + 1;
            let mut buf = String::new();
            let mut esc = false;
            while j < bytes.len() {
                let c = bytes[j];
                if esc {
                    buf.push(c as char);
                    esc = false;
                } else if c == b'\\' {
                    esc = true;
                } else if c == b'"' {
                    break;
                } else {
                    buf.push(c as char);
                }
                j += 1;
            }
            out.push(buf);
            i = j + 1;
        } else {
            i += 1;
        }
    }
    out
}

fn extract_first_string_literal(s: &str) -> Option<String> {
    extract_string_literals(s).into_iter().next()
}

/// Find the byte index where `method` `==` `"..."` starts inside the
/// region. Tolerant of whitespace/newlines between the three tokens.
fn find_method_eq(region: &str) -> Option<usize> {
    let mut from = 0;
    while let Some(rel) = region[from..].find("method") {
        let abs = from + rel;
        let after = abs + "method".len();
        let rest = region[after..].trim_start();
        if rest.starts_with("==") {
            let eq_end = after + (region.len() - after - rest.len()) + 2;
            let after_eq = region[eq_end..].trim_start();
            if after_eq.starts_with('"') {
                return Some(abs);
            }
        }
        from = abs + 1;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_matches_arm() {
        let src = r#"
            if receiver_is_pandas_inherited
                && matches!(method, "head" | "tail" | "first" | "take")
                && PANDAS_INHERITED_ARMS.contains(&method)
            {
                return Some(receiver);
            }
        "#;
        let mut got = extract_methods(src);
        got.sort();
        assert_eq!(got, vec!["first", "head", "take", "tail"]);
    }

    #[test]
    fn extracts_method_eq_inline() {
        let src = r#"
            if receiver_is_pandas_inherited && method == "assign" {
                return None;
            }
        "#;
        let got = extract_methods(src);
        assert_eq!(got, vec!["assign"]);
    }

    #[test]
    fn extracts_method_eq_multiline() {
        let src = r#"
            if receiver_is_pandas_inherited
                && method == "rename"
                && let Some(dict) = pandas_dict_kwarg(call, "columns")
            {
                return Some(apply_rename_dict(dict, &receiver, ctx));
            }
        "#;
        let got = extract_methods(src);
        assert_eq!(got, vec!["rename"]);
    }

    #[test]
    fn ignores_binding_line() {
        // The `let receiver_is_pandas_inherited = ...` line is the
        // definition of the gate, not an arm. Must not panic, must not
        // collect.
        let src = r#"
            let receiver_is_pandas_inherited = receiver_dialect == Some(Dialect::Pandas);
            if receiver_is_pandas_inherited && method == "melt" {
                return None;
            }
        "#;
        let got = extract_methods(src);
        assert_eq!(got, vec!["melt"]);
    }

    #[test]
    fn negative_space_simulated_new_arm_grows_inventory() {
        // v1.8 spec §2.1 negative-space test: a contributor adding a new
        // arm in `expr.rs` causes the extraction to grow.
        let baseline = r#"
            if receiver_is_pandas_inherited
                && matches!(method, "head" | "tail")
            { return Some(receiver); }
            if receiver_is_pandas_inherited && method == "assign" { return None; }
        "#;
        let added = r#"
            if receiver_is_pandas_inherited
                && matches!(method, "head" | "tail")
            { return Some(receiver); }
            if receiver_is_pandas_inherited && method == "assign" { return None; }
            if receiver_is_pandas_inherited && method == "foobar" { return None; }
        "#;
        let mut base = extract_methods(baseline);
        let mut grew = extract_methods(added);
        base.sort();
        grew.sort();
        assert_eq!(base, vec!["assign", "head", "tail"]);
        assert_eq!(grew, vec!["assign", "foobar", "head", "tail"]);
        assert_eq!(grew.len(), base.len() + 1);
    }

    #[test]
    fn negative_space_simulated_removed_arm_shrinks_inventory() {
        // Mirror of the above — removing an arm shrinks the extraction.
        let with_arm = r#"
            if receiver_is_pandas_inherited && method == "melt" { return None; }
            if receiver_is_pandas_inherited && method == "assign" { return None; }
        "#;
        let without_arm = r#"
            if receiver_is_pandas_inherited && method == "assign" { return None; }
        "#;
        let mut a = extract_methods(with_arm);
        let mut b = extract_methods(without_arm);
        a.sort();
        b.sort();
        assert_eq!(a, vec!["assign", "melt"]);
        assert_eq!(b, vec!["assign"]);
        assert_eq!(a.len(), b.len() + 1);
    }

    #[test]
    fn ignores_method_literals_inside_line_comments() {
        // The tripwire comment in expr.rs documents the build.rs's
        // matched arm shapes — and quotes the patterns. The build.rs
        // must NOT extract method names from inside line comments.
        let src = r#"
            // receiver_is_pandas_inherited && matches!(method, "FAKE_A" | "FAKE_B")
            // receiver_is_pandas_inherited && method == "FAKE_C"
            if receiver_is_pandas_inherited && method == "real" { return None; }
        "#;
        let stripped = strip_line_comments(src);
        let got = extract_methods(&stripped);
        assert_eq!(got, vec!["real"]);
    }

    #[test]
    fn strip_line_comments_preserves_string_literals_with_slashes() {
        let src = r#"let s = "// not a comment";
let real = "v";"#;
        let stripped = strip_line_comments(src);
        assert!(stripped.contains("\"// not a comment\""));
        assert!(stripped.contains("\"v\""));
    }

    #[test]
    fn extracts_full_v17_inventory_from_synthetic_fixture() {
        // Spec §2.1 positive test: feed in a synthetic fixture mirroring
        // the v1.7-HEAD shape of expr.rs and verify the extractor
        // recovers exactly the 9 methods the hand inventory pins.
        let src = r#"
            let receiver_is_pandas_inherited = receiver_dialect == Some(Dialect::Pandas);
            if receiver_is_pandas_inherited
                && matches!(method, "head" | "tail" | "first" | "take")
            { return Some(receiver); }
            if receiver_is_pandas_inherited
                && method == "rename"
                && let Some(dict) = pandas_dict_kwarg(call, "columns")
            { return Some(apply_rename_dict(dict, &receiver, ctx)); }
            if receiver_is_pandas_inherited && method == "assign" {
                return Some(apply_pandas_assign(call));
            }
            if receiver_is_pandas_inherited
                && method == "drop"
                && let Some(list) = pandas_list_kwarg(call, "columns")
            { return Some(apply_pandas_drop_columns(list)); }
            if receiver_is_pandas_inherited
                && method == "drop"
                && pandas_list_kwarg(call, "columns").is_none()
            { return Some(receiver); }
            if receiver_is_pandas_inherited && method == "pivot_table" { return None; }
            if receiver_is_pandas_inherited && method == "melt" { return None; }
        "#;
        let mut got = extract_methods(src);
        got.sort();
        got.dedup();
        assert_eq!(
            got,
            vec![
                "assign",
                "drop",
                "first",
                "head",
                "melt",
                "pivot_table",
                "rename",
                "tail",
                "take",
            ]
        );
        assert_eq!(got.len(), 9);
    }
}
