//! v1.8 PR-A1 — generate `PANDAS_INHERITED_ARM_METHODS_GENERATED` from
//! the live `operations/expr.rs` source.
//!
//! v1.7 retro rule 4: the hand-maintained inventory in
//! `tests/v17_pr_a1_dialect_signals_guard.rs` drifted within a single
//! cycle (PR-D1 added a `melt` arm; the hand-list missed it; PR-G
//! patched). The fix is to make the inventory a build-time extraction
//! from the source-of-truth `expr.rs`. A consumer-side equality test
//! (`v18_pr_a1_hand_inventory_matches_generated`) then keeps the
//! hand-list honest, OR makes deletion trivial.
//!
//! Patterns matched (both are gated by `receiver_is_pandas_inherited &&`):
//!
//!   • `receiver_is_pandas_inherited && matches!(method, "A" | "B" | ...)`
//!     — multi-line tolerant; extracts every string literal inside the
//!     `matches!` arm list.
//!   • `receiver_is_pandas_inherited && method == "X"`
//!     — multi-line tolerant; extracts the single string literal.
//!
//! If you change the syntax of either pattern in `expr.rs`, update
//! `extract_methods` in `src/build_helpers.rs` in lockstep. The
//! tripwire comment near the first `receiver_is_pandas_inherited` use
//! in `expr.rs` names this file. v1.9 PR-A1 R2: pure logic lives in
//! `src/build_helpers.rs` so it's exercisable by an integration test
//! under `tests/build_helpers.rs` (`cargo test --workspace` does NOT
//! run build-script inline `mod tests`).

#[path = "src/build_helpers.rs"]
mod build_helpers;

use build_helpers::{extract_methods, strip_line_comments};
use std::env;
use std::fs;
use std::path::PathBuf;

const EXPR_RS_RELATIVE: &str = "src/operations/expr.rs";

fn main() {
    println!("cargo:rerun-if-changed={EXPR_RS_RELATIVE}");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/build_helpers.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo");
    let expr_path = PathBuf::from(&manifest_dir).join(EXPR_RS_RELATIVE);
    let raw = fs::read_to_string(&expr_path)
        .unwrap_or_else(|e| panic!("read {}: {}", expr_path.display(), e));
    let source = strip_line_comments(&raw);

    let mut methods = extract_methods(&source);
    methods.sort();
    methods.dedup();

    let entries = methods
        .iter()
        .map(|m| format!("    {:?},", m))
        .collect::<Vec<_>>()
        .join("\n");
    let generated = format!(
        "// @generated by crates/pykrete/build.rs — do not edit by hand.\n\
         //\n\
         // Extracted from `src/operations/expr.rs` by scanning for the two\n\
         // `receiver_is_pandas_inherited &&` arm shapes. Re-run on every\n\
         // `cargo build` (cargo:rerun-if-changed). Consumed by\n\
         // `dialect_signals.rs` (re-export) and by\n\
         // `tests/v17_pr_a1_dialect_signals_guard.rs` (equality tripwire).\n\
         pub const PANDAS_INHERITED_ARM_METHODS_GENERATED: &[&str] = &[\n{entries}\n];\n"
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let out_path = PathBuf::from(&out_dir).join("pandas_inherited_arm_methods.rs");
    fs::write(&out_path, generated)
        .unwrap_or_else(|e| panic!("write {}: {}", out_path.display(), e));
}
