[workspace]
members = ["crates/pykrete", "crates/pykrete-lsp", "crates/pykrete-wasm"]
resolver = "2"

[workspace.package]
version = "1.5.5"
edition = "2024"
license = "MIT"
repository = "https://github.com/amirnaderi93/pykrete"

[workspace.dependencies]
# Shared/pinned dependencies will go here as we add crates.

[profile.dev]
# Faster dev builds at the cost of less optimization.
opt-level = 0
debug = "line-tables-only"

[profile.release]
lto = "thin"
codegen-units = 1
