#!/usr/bin/env bash
#
# Renders the Homebrew formula for pykrete.
#
# The release workflow (.github/workflows/release.yml) runs this with the
# release version and the three platform checksums set, and writes the
# output to the tap's Formula/pykrete.rb. It is the single source of truth
# for the formula's shape — edit the formula here, not in the tap.
#
# Required environment:
#   VERSION          release version, no leading "v" (e.g. 0.1.0)
#   SHA_DARWIN_ARM    sha256 of the aarch64-apple-darwin tarball
#   SHA_DARWIN_X64    sha256 of the x86_64-apple-darwin tarball
#   SHA_LINUX_X64     sha256 of the x86_64-unknown-linux-gnu tarball
set -euo pipefail

cat <<EOF
# pykrete Homebrew formula — generated by the pykrete release workflow.
# Do not edit by hand; changes are overwritten on the next release.
class Pykrete < Formula
  desc "Static schema checking for PySpark dataframes"
  homepage "https://github.com/amirnaderi93/pykrete"
  version "${VERSION}"
  license "MIT"

  base = "https://github.com/amirnaderi93/pykrete/releases/download/v#{version}"

  on_macos do
    on_arm do
      url "#{base}/pykrete-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "${SHA_DARWIN_ARM}"
    end
    on_intel do
      url "#{base}/pykrete-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "${SHA_DARWIN_X64}"
    end
  end

  on_linux do
    on_intel do
      url "#{base}/pykrete-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${SHA_LINUX_X64}"
    end
  end

  def install
    bin.install "pykrete"
    bin.install "pykrete-lsp"
  end

  test do
    assert_match "pykrete", shell_output("#{bin}/pykrete --help 2>&1")
  end
end
EOF
