/**
 * Monarch tokenizer override for Monaco's bundled `python` language.
 *
 * Identical to `monaco-editor/esm/vs/basic-languages/python/python.js`
 * (v0.52.2) except for one change: an identifier that appears after a
 * `.` is always tokenized as a plain `identifier`, never matched against
 * `@keywords`. That keeps method calls like `df.filter(...)`,
 * `s.map(...)`, `xs.sum()` from inheriting the keyword color that
 * Monaco's Python tokenizer otherwise applies to `filter` / `map` /
 * `sum` / `len` / `type` / `print` / `range` / etc. when they appear as
 * bare identifiers (Python builtins live in the same `keywords` list as
 * `def` / `class` / `return`).
 *
 * Stock VS Code's Python grammar has the same quirk because its
 * tokenizer is also context-free; in the playground we own the
 * tokenizer and can fix it.
 */

import type { languages } from 'monaco-editor';

export const pykretePythonLanguage: languages.IMonarchLanguage = {
  defaultToken: '',
  tokenPostfix: '.python',
  keywords: [
    'False',
    'None',
    'True',
    '_',
    'and',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'case',
    'class',
    'continue',
    'def',
    'del',
    'elif',
    'else',
    'except',
    'exec',
    'finally',
    'for',
    'from',
    'global',
    'if',
    'import',
    'in',
    'is',
    'lambda',
    'match',
    'nonlocal',
    'not',
    'or',
    'pass',
    'print',
    'raise',
    'return',
    'try',
    'type',
    'while',
    'with',
    'yield',
    'int',
    'float',
    'long',
    'complex',
    'hex',
    'abs',
    'all',
    'any',
    'apply',
    'basestring',
    'bin',
    'bool',
    'buffer',
    'bytearray',
    'callable',
    'chr',
    'classmethod',
    'cmp',
    'coerce',
    'compile',
    'complex',
    'delattr',
    'dict',
    'dir',
    'divmod',
    'enumerate',
    'eval',
    'execfile',
    'file',
    'filter',
    'format',
    'frozenset',
    'getattr',
    'globals',
    'hasattr',
    'hash',
    'help',
    'id',
    'input',
    'intern',
    'isinstance',
    'issubclass',
    'iter',
    'len',
    'locals',
    'list',
    'map',
    'max',
    'memoryview',
    'min',
    'next',
    'object',
    'oct',
    'open',
    'ord',
    'pow',
    'print',
    'property',
    'reversed',
    'range',
    'raw_input',
    'reduce',
    'reload',
    'repr',
    'reversed',
    'round',
    'self',
    'set',
    'setattr',
    'slice',
    'sorted',
    'staticmethod',
    'str',
    'sum',
    'super',
    'tuple',
    'type',
    'unichr',
    'unicode',
    'vars',
    'xrange',
    'zip',
    '__dict__',
    '__methods__',
    '__members__',
    '__class__',
    '__bases__',
    '__name__',
    '__mro__',
    '__subclasses__',
    '__init__',
    '__import__',
  ],
  brackets: [
    { open: '{', close: '}', token: 'delimiter.curly' },
    { open: '[', close: ']', token: 'delimiter.bracket' },
    { open: '(', close: ')', token: 'delimiter.parenthesis' },
  ],
  tokenizer: {
    root: [
      { include: '@whitespace' },
      { include: '@numbers' },
      { include: '@strings' },
      [/\.(?=[a-zA-Z_])/, 'delimiter', '@property'],
      [/[,:;]/, 'delimiter'],
      [/[{}\[\]()]/, '@brackets'],
      [/@[a-zA-Z_]\w*/, 'tag'],
      [
        /[a-zA-Z_]\w*/,
        {
          cases: {
            '@keywords': 'keyword',
            '@default': 'identifier',
          },
        },
      ],
    ],
    property: [[/[a-zA-Z_]\w*/, 'identifier', '@pop']],
    whitespace: [
      [/\s+/, 'white'],
      [/(^#.*$)/, 'comment'],
      [/'''/, 'string', '@endDocString'],
      [/"""/, 'string', '@endDblDocString'],
    ],
    endDocString: [
      [/[^']+/, 'string'],
      [/\\'/, 'string'],
      [/'''/, 'string', '@popall'],
      [/'/, 'string'],
    ],
    endDblDocString: [
      [/[^"]+/, 'string'],
      [/\\"/, 'string'],
      [/"""/, 'string', '@popall'],
      [/"/, 'string'],
    ],
    numbers: [
      [/-?0x([abcdef]|[ABCDEF]|\d)+[lL]?/, 'number.hex'],
      [/-?(\d*\.)?\d+([eE][+\-]?\d+)?[jJ]?[lL]?/, 'number'],
    ],
    strings: [
      [/'$/, 'string.escape', '@popall'],
      [/f'{1,3}/, 'string.escape', '@fStringBody'],
      [/'/, 'string.escape', '@stringBody'],
      [/"$/, 'string.escape', '@popall'],
      [/f"{1,3}/, 'string.escape', '@fDblStringBody'],
      [/"/, 'string.escape', '@dblStringBody'],
    ],
    fStringBody: [
      [/[^\\'\{\}]+$/, 'string', '@popall'],
      [/[^\\'\{\}]+/, 'string'],
      [/\{[^\}':!=]+/, 'identifier', '@fStringDetail'],
      [/\\./, 'string'],
      [/'/, 'string.escape', '@popall'],
      [/\\$/, 'string'],
    ],
    stringBody: [
      [/[^\\']+$/, 'string', '@popall'],
      [/[^\\']+/, 'string'],
      [/\\./, 'string'],
      [/'/, 'string.escape', '@popall'],
      [/\\$/, 'string'],
    ],
    fDblStringBody: [
      [/[^\\"\{\}]+$/, 'string', '@popall'],
      [/[^\\"\{\}]+/, 'string'],
      [/\{[^\}':!=]+/, 'identifier', '@fStringDetail'],
      [/\\./, 'string'],
      [/"/, 'string.escape', '@popall'],
      [/\\$/, 'string'],
    ],
    dblStringBody: [
      [/[^\\"]+$/, 'string', '@popall'],
      [/[^\\"]+/, 'string'],
      [/\\./, 'string'],
      [/"/, 'string.escape', '@popall'],
      [/\\$/, 'string'],
    ],
    fStringDetail: [
      [/[:][^}]+/, 'string'],
      [/[!][ars]/, 'string'],
      [/=/, 'string'],
      [/\}/, 'identifier', '@pop'],
    ],
  },
};
